// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCAE_bsBH77TIibFVqRVpVZ3HSToZktDL0',
    appId: '1:743403898251:web:25f9d62bc37a3491bd5b8e',
    messagingSenderId: '743403898251',
    projectId: 'quizapp4-6a5b2',
    authDomain: 'quizapp4-6a5b2.firebaseapp.com',
    storageBucket: 'quizapp4-6a5b2.appspot.com',
    measurementId: 'G-K01ZMXBETD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA228hykkdBob_YX1a_SFuoQ5Q1zcvFzs',
    appId: '1:743403898251:android:18ed71430997258fbd5b8e',
    messagingSenderId: '743403898251',
    projectId: 'quizapp4-6a5b2',
    storageBucket: 'quizapp4-6a5b2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_iiODtHFT3IjrhiJBOlLQg4Y3RR2cIA',
    appId: '1:743403898251:ios:58057dddf841b297bd5b8e',
    messagingSenderId: '743403898251',
    projectId: 'quizapp4-6a5b2',
    storageBucket: 'quizapp4-6a5b2.appspot.com',
    iosBundleId: 'com.example.quizapp4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCAE_bsBH77TIibFVqRVpVZ3HSToZktDL0',
    appId: '1:743403898251:web:2df9523ec5eaa27ebd5b8e',
    messagingSenderId: '743403898251',
    projectId: 'quizapp4-6a5b2',
    authDomain: 'quizapp4-6a5b2.firebaseapp.com',
    storageBucket: 'quizapp4-6a5b2.appspot.com',
    measurementId: 'G-399Z1LNZV9',
  );
}
